# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce5030ce9d20ec813ebb8b36e5890940d283137318e276a7ac4c25930f020ae7b4e59efc2f4331b909b0860ca9555a41f48ed7f5ea998531b7f0cd549a58774c

test:
  secret_key_base: 9349afdc6c27cd2fa7734704906fb3df9215ece65e90046006a77b3d493f726c516f1e3ba89bfa56ae75a61948f24c6d61ee51a0cf23bb67433b9e815fc2a73d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
